safe: true
lsi: true
pygments: true
markdown: kramdown
navigation:
  - text: Home
    url: /index.html
  - text: Imprint
    url: /imprint.html
baseurl: http://georg.io
imgbase: https://dl.dropboxusercontent.com/u/129945779/georgio
description: "Personal weblog of Georg R Walther. \
              Programming, data analysis, data visualization, machine learning, \
              modelling, dynamical systems, numerical analysis, and
              web applications in Python, C, and JavaScript."
author:
  name: Georg R Walther
  email: contact@georg.io
  nick: waltherg
  profiles:
    - label: GitHub
      url: https://github.com/waltherg
    - label: Twitter
      url: https://twitter.com/mbgrw
title: georg.io
permalink: /:year/:month/:title
disqus:
  config:
    - label: disqus_shortname
      value: 'georgio'
googleanalytics:
  account: UA-45212489-1
