safe: true
lsi: true
pygments: true
navigation:
  - text: Home
    url: /index.html
  - text: Imprint
    url: /imprint.html
baseurl: http://georg.io
description: "Personal webpage by Georg R Walther. \
              I discuss programming and data anlysis in Python, C, JavaScript, \
              and other languages. \
              My main interests lie with numerical methods / numerical analysis, \
              consuming web API services, and tinkering with web applications. \
              I strive to learn more about data analysis, \
              statistical analysis, and machine learning."              
author:
  name: Georg R Walther
  email: contact@georg.io
  nick: waltherg
  profiles:
    - label: GitHub
      url: https://github.com/waltherg
    - label: Twitter
      url: https://twitter.com/mbgrw
title: georg.io
disqus:
  config:
    - label: disqus_shortname
      value: 'georgio'
googleanalytics:
  account: UA-45212489-1